title: Simulations of a 2-in-1 Exhibition
description: A series of pop-up artistic installations hosted inside of ground-based walls which are painted and designed for the awalkaday.art Photo Collection.
theme: jekyll-theme-slate 
